services:
  profile:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - "8080:80"
    expose:
      - "80"
    command: ["nginx", "-g", "daemon off;"]
