version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./build:/app/build
    depends_on:
      - nginx
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./build:/usr/share/nginx/html
    networks:
      - app-network
    command: ["nginx", "-g", "daemon off;"]

networks:
  app-network:
    driver: bridge
