---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: gil-deployment
  
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: gil
      
  template:
    metadata:
      labels:
        app: gil
        
    spec:
      containers:
      - name: gil
        image: gil
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service

metadata:
  name: gil-service
  
spec:
  selector:
    app: gil
    
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
      
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: nginx
      
  template:
    metadata:
      labels:
        app: nginx
        
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service

metadata:
  name: nginx-service
  
spec:
  selector:
    app: nginx
    
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
  type: LoadBalancer