trigger:
  branches:
    include:
      - k8s

pool: K8S

variables:
  - group: 
      K8s-Pipeline

steps:
- task: printAllVariables@1
  displayName: 'Print all variables'

# Apply Kubernetes manifest
- task: Bash@3
  displayName: 'Run K8S Deployment'
  inputs:
    targetType: 'inline'
    script: |
      echo "$(SUDO_PASSWORD)" | sudo -S kubectl apply -f Pipelines/k8s_manifest.yml

# Wait for K8S pods to be ready
- task: Bash@3
  displayName: 'Wait for Pods to be Ready'
  inputs:
    targetType: 'inline'
    script: |
      echo "$(SUDO_PASSWORD)" | sudo -S kubectl wait --for=condition=ready pod -l app=gil -n gil-namespace --timeout=300s

# Wait for testing (manual 10-minute delay)
- task: Bash@3
  displayName: 'Wait for Testing'
  inputs:
    targetType: 'inline'
    script: |
      echo "Waiting for 10 minutes to test the container"; sleep 600
